cluster:
  url: "https://localhost:50737"
  username: "elastic"
  password: "9Fj1dUB9r9k5Fqj76yF1Co48"

aliases:
  - name: "cluster-logs"
    max_size: "20GB"
  - name: "non-existant"
    max_size: "pizza"