apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es-index-pruner.fullname" . }}
  labels:
    {{- include "es-index-pruner.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "es-index-pruner.tplvalues.render" (dict "value" .Values.config "scope" .) | toYaml | nindent 4 }}
